app/models.py
from flask_login import UserMixin
from app import login, db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(36), nullable=False)
  email = db.Column(db.String(36), nullable=False, index=True, unique=True)
  password = db.Column(db.String(32), nullable=False)
  created = db.Column(db.DateTime, default=datetime.utcnow)
  modified = db.Column(db.DateTime, default=datetime.utcnow)
  posts = db.relationship('Post', backref='author', lazy='dynamic')
  
  def set_password(self, password):
    self.password = generate_password_hash(password)
    
  def check_password(self, password):
    return check_password_hash(self.password, password)
    
class Tool(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(36), nullable=False)
  author = db.Column(db.String(50), nullable=False)
  alias = db.Column(db.String(50), nullable=True)
  custom_alias = db.Column(db.String(50), nullable=True)
  name_repo = db.Column(db.String(50), nullable=True)
  type_install = db.Column(db.String(50), nullable=False)
  category = db.Column(db.String(50), nullable=False)
  dependencies = db.Column(db.String(50), nullable=True)
  created = db.Column(db.DateTime, default=datetime.utcnow)
  modified = db.Column(db.DateTime, default=datetime.utcnow)
  
class Post(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  body = db.Column(db.String(500), nullable=False)
  created = db.Column(db.DateTime, default=datetime.utcnow)
  modified = db.Column(db.DateTime, default=datetime.utcnow)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
  
@login.user_loader
def load_user(id):
  return User.query.get(int(id))
  
  

app/comunidade/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import DataRequired

class ComunidadeForm(FlaskForm):
  body = TextAreaField('Sugestão', validators=[DataRequired()])
  submit = SubmitField('Publicar')

app/tool/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired

type_install = ['apt', 'git']
categories = [
    "Information Collection",
    "Vulnerability Analysis",
    "Wireless Attacks",
    "Web Applications",
    "Sniffing and Faking",
    "Maintaining Access",
    "Reporting Tools",
    "Exploitation Tools",
    "Forensic Tools",
    "Stress Test",
    "Password Attacks",
    "Reverse Engineering",
    "Hardware Hacking",
    "Extra"
]

class RegisterToolForm(FlaskForm):
  name = StringField('Nome', validators=[DataRequired()])
  author = StringField('Autor', validators=[DataRequired()])
  alias = StringField('Apelido')
  custom_alias = StringField('Apelido customizado')
  name_repo = StringField('Nome do repositório')
  type_install = SelectField('Instalaçã via', choices=type_install, default='apt', validators=[DataRequired()])
  category = SelectField('Categoria', choices=categories, default='Extra', validators=[DataRequired()])
  dependencies = StringField('Dependencias')
  submit = SubmitField('Cadastrar')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_bootstrap import Bootstrap5
from flask_moment import Moment
from config import Config

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap5()
login = LoginManager()
login.login_view = 'auth.entrar'
login.login_message = 'Página restrita, faça login para ter acesso'
moment = Moment()

def create_app(class_config=Config):
  app = Flask(__name__)
  app.config.from_object(class_config)
  db.init_app(app)
  migrate.init_app(app, db)
  bootstrap.init_app(app)
  login.init_app(app)
  moment.init_app(app)
  
  # rotas de auth
  from app.auth import bp as auth_bp
  app.register_blueprint(auth_bp, prefix='/auth')
  # Rotas de main
  from app.main import bp as main_bp
  app.register_blueprint(main_bp)
  # Rotas de tool
  from app.tool import bp as tool_bp
  app.register_blueprint(tool_bp)
  # Rotas de comunidade
  from app.comunidade import bp as comunidade_bp
  app.register_blueprint(comunidade_bp)
  # Rotas de user
  from app.user import bp as user_bp
  app.register_blueprint(user_bp)
  
  return app
from app import models

app/comunidade/__init__.py
from flask import Blueprint

bp = Blueprint('comunidade', __name__)

from app.comunidade import routes

app/comunidade/routes.py
from app.comunidade import bp
from flask import render_template, request, current_app, url_for, redirect, flash
from flask_login import current_user
from app.comunidade.forms import ComunidadeForm
from app.models import Post
from app import db

@bp.route('/comunidade', methods=['GET', 'POST'])
def comunidade():
  if not current_user.is_authenticated:
    flash('Página restrita, faça login para acessá-la')
    return redirect(url_for('auth.entrar', next=url_for('comunidade.comunidade')))
    
  form = ComunidadeForm()
  if form.validate_on_submit():
    post = Post(body=form.body.data, author=current_user)
    db.session.add(post)
    db.session.commit()
    
  page = request.args.get('page', 1, type=int)
  posts = Post.query.order_by(Post.created.desc()).paginate(page=page, per_page=current_app.config['PER_PAGE'], error_out=False)
  next_url = url_for('comunidade.comunidade', page=posts.next_num) if posts.has_next else None
  prev_url = url_for('comunidade.comunidade', page=posts.prev_num) if posts.has_prev else None
  return render_template(
    'comunidade/comunidade.html', 
    title='Comunidade', 
    form=form, 
    posts=posts.items, 
    prev_url=prev_url, 
    next_url=next_url)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import (
  render_template, 
  url_for,
  redirect, 
  flash
)
from flask_login import current_user
from app.main import bp

@bp.route('/')
def inicio():
  if current_user.is_authenticated:
    return redirect(url_for('user.usuarios'))
  return render_template('main/inicio.html', title='inicio')

app/tool/__init__.py
from flask import Blueprint

bp = Blueprint('tool', __name__)

from app.tool import routes

app/tool/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user
from app.tool import bp
from app.models import Tool
from app.tool.forms import RegisterToolForm
from app import db

@bp.route('/ferramentas')
def ferramentas():
  if not current_user.is_authenticated:
    flash('Página restrita, faça login para acessá-la')
    return redirect(url_for('auth.entrar', next=url_for('tool.ferramentas')))
    
  tool = Tool.query.all()
  return render_template('tool/ferramentas.html', title='Ferramentas', tools=tool)
  
@bp.route('/cadastrar', methods=['GET', 'POST'])
def cadastrar():
  if not current_user.is_authenticated:
    flash('Página restrita, faça login para accesá-la')
    return redirect(url_for('auth.entrar', next=url_for('tool.cadastrar')))
    
  form = RegisterToolForm()
  
  if form.validate_on_submit():
    tool = Tool(
      name=form.name.data,
      author=form.author.data,
      alias=form.alias.data,
      custom_alias=form.custom_alias.data,
      name_repo=form.name_repo.data,
      type_install=form.type_install.data,
      category=form.category.data,
      dependencies=form.dependencies.data
    )
    db.session.add(tool)
    db.session.commit()
    flash('Ferramenta registrada com sucesso')
    return redirect(url_for('tool.ferramentas'))
  
  return render_template('tool/cadastrar.html', title='Cadastrar', form=form)

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
from app.user import bp
from flask import request, render_template, current_app, url_for, redirect, flash
from flask_login import current_user
from app.models import User

@bp.route('/usuarios')
def usuarios():
  if not current_user.is_authenticated:
    flash('Página restrita, faça login para acessá-la')
    return redirect(url_for('auth.entrar', next=url_for('user.usuarios')))
    
  page = request.args.get('page', 1, type=int)
  usuarios = User.query.order_by(User.created.desc()).paginate(page=page, per_page=current_app.config['PER_PAGE'], error_out=False)
  next_url = url_for('user.usuarios', usuarios.next_num) if usuarios.has_next else None
  prev_url = url_for('user.usuarios', usuarios.prev_num) if usuarios.has_prev else None
  return render_template(
    'user/usuarios.html',
    title='Usuários',
    usuarios=usuarios.items,
    next_url=next_url,
    prev_url=prev_url)

app/templates/_message.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
    <div class="container">
      <p class="alert alert-info mt-3">
        {{ message }}
      </p>
    </div>
    {% endfor %}
  {% endif %}
{% endwith %}

app/templates/base.html
<!doctype html>
<html lang="pt-br">
  <head>
  {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    {% block styles %}
      <!-- Bootstrap css -->
      {{ bootstrap.load_css() }}
    {% endblock %}
    <title>{{ title }} - Tela</title>
  {% endblock %}
  </head>
  <body>
    <!-- Navigation -->
    {% include 'navigation.html' %}
    <!-- Message -->
    {% include '_message.html' %}
    <!-- Your page content -->
    {% block content %}{% endblock %}
    {% block scripts %}
      <!-- Javascript optional -->
      {{ bootstrap.load_js() }}
      {{ moment.include_moment() }}
    {% endblock %}
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
  </body>
</html>

app/templates/comunidade/comunidade.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}
{% block content %}
<div class="container mt-5">
  <h2>{{ title }}</h2>
  <form action="" method="post">
    {{ render_form(form) }}
  </form>
  
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">Atualizaçôes recentes:</h6>
    {% for post in posts %}
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <span class="d-flex justify-content-between">
          <strong class="d-block text-gray-dark">{{ post.author.name }}</strong>
          <strong>{{ moment(post.created).fromNow() }}</strong>
        </span><br>
        {{ post.body }} <br><br>
        <a href="#">Editar</a>
        <a href="#">Apagar</a>
      </p>
    </div>
    {% endfor %}
    <nav aria-label="Page" class="mt-4">
      <ul class="pagination justify-content-around">
        <li class="previous{% if not prev_url %} disabled {% endif %}">
          <a class="page-link" href="{{ prev_url or '#' }}"><span> &larr;</span> recentes</a>
        </li>
        <li class="next{% if not next_url %} disabled {% endif %}">
          <a class="page-link" href="{{ next_url or '#' }}">Antigas <span>&rarr;</span></a>
        </li>
      </ul>
    </nav>
  </div>
</div>
{% endblock %}

app/templates/main/inicio.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid sobre">
  <div class="container">
    <h2 class="text-center display-3 mb-3">Sobre</h2>
    <p class="lead text-center">
      Toolmux é uma ferramenta que ajuda você a instalar várias ferramentas de testes de penetração e ferramentas de hacking no sistema Android com facilidade.
    </p>
  </div>
</div>

<div class="container-fluid transferencia">
  <div class="container">
    <h2 class="text-center display-4">Transferência</h2>
    <div class="text-center">
      <p class="lead">Toolmux instalador de ferramentas para o termux emulador<br><br>
      <a href="https://github.com/Olliv3r/toolmux" class="btn btn-primary mb-3" role='button' target="_blank">Download</a>
      </p>
    </div>
  </div>
</div>
<div class="container-fluid comunidade">
  <div class="container">
    <div class="text-center">
      <h2 class="display-4">Comumidade</h2>
      <p class="lead">Participe da comunidade e publique as suas sugestôes<br><br>
      <a href="{{ url_for('auth.registrar') }}" class="btn btn-outline-primary mb-3" role="button">Registre-se</a>
      </p>
    </div>
  </div>
</div>

{% endblock %}

app/templates/navigation.html
<header>
  <nav class="navbar navbar-expand-md bg-primary" data-bs-theme="dark">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.inicio') }}">Toolmux</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-sm-flex justify-content-sm-between" id="navbarSupportedContent">
        <ul class="navbar-nav mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('main.inicio') }}">Home</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('tool.ferramentas') }}">Ferramentas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.usuarios') }}">Usuários</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.profile') }}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('comunidade.comunidade') }}">Comunidade</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav mb-lg-0">
        {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a href="{{ url_for('auth.entrar') }}" class="nav-link">Entrar</a>
          </li>
        {% else %}
        <li class="nav-item">
            <a href="{{ url_for('auth.sair') }}" class="nav-link">Sair</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

app/templates/tool/cadastrar.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}
{% block content %}
<div class="container">
  <h2>{{ title }}</h2>
  <form action="" method="post">
    {{ render_form(form) }}
  </form>
</div>
{% endblock %}

app/templates/tool/ferramentas.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
  <h1>{{ title }}</h1>
  {% if tools %}
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Autor</th>
        <th>Criado</th>
        <th>Ação</th>
      </tr>
    </thead>
    <tbody>
      {% for tool in tools %}
      <tr>
        <td>{{ tool.id }}</td>
        <td>{{ tool.name }}</td>
        <td>{{ tool.author }}</td>
        <td>{{ tool.created }}</td>
        <td>Apagar</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="alert alert-light text-center mt-3 mb-3">Nenhuma ferramenta encontrada</p>
  <a href="{{ url_for('tool.cadastrar') }}" class="btn btn-outline-success">Cadastrar</a>
  {% endif %}
</div>
{% endblock %}

app/templates/user/usuarios.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-3">
  <h2>{{ title }}</h2>
  {% if usuarios %}
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Criado</th>
        <th>Ação</th>
      </tr>
    </thead>
    <tbody>
      {% for usuario in usuarios %}
      <tr>
        <td>{{ usuario.id }}</td>
        <td>{{ usuario.name }}</td>
        <td>{{ usuario.email }}</td>
        <td>{{ usuario.created }}</td>
        <td>Apagar</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p class="alert alert-light text-center mt-3 mb-3">Nenhum usuário encontrada</p>
  <a href="{{ url_for('auth.registrar') }}" class="btn btn-outline-success">Cadastrar</a>
  {% endif %}
</div>
{% endblock %}